#!/bin/bash

# Debugging / Logging
set -x
exec > >(tee /var/log/user-data.log|logger -t user-data ) 2>&1
echo BEGIN
date '+%Y-%m-%d %H:%M:%S'

# Patch the system on first boot
yum update -y

export OCI_CLI_AUTH=instance_principal
export PATH="$PATH:/usr/bin"
export HOME="/opt/oci-caas/cinc"
export CHEF_HOME=$HOME
export PACKAGE_CACHE="$HOME/package_cache"

mkdir -p $PACKAGE_CACHE
cd $CHEF_HOME

oci os object get -bn ${bootstrap_bucket} --file $PACKAGE_CACHE/${bootstrap_bundle} --name ${bootstrap_bundle}
oci os object get -bn ${bootstrap_bucket} --file $PACKAGE_CACHE/cinc-${cinc_version}.el7.x86_64.rpm --name cinc-${cinc_version}.el7.x86_64.rpm

gzip -dc $PACKAGE_CACHE/${bootstrap_bundle} | tar -xvf -
rpm -i $PACKAGE_CACHE/cinc-${cinc_version}.el7.x86_64.rpm

# Write JSON file used for Cinc attributes
cat << EOF > $CHEF_HOME/attributes.json
{
    "package_cache": "$PACKAGE_CACHE",
    "backup_bucket_name": "${backup_bucket_name}",
    "wazuh_user": "${wazuh_user}",
    "wazuh_password": "${wazuh_password}"
}
EOF

# Temporarily disable SELinux - required for firewalld updates during user-data
setenforce 0

# Run the Cinc client
cinc-client -z --runlist wazuh_server -j $CHEF_HOME/attributes.json

# Re-enable SELinux
setenforce 1